name: Deploy Remote

on:  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HOST: root@80.93.190.84
      DEPLOY_DIRECTORY: /var/www
      NGINX_DIRECTORY: /etc/nginx/sites-available

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            dist
            .nuxt
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-

      - name: Install dependencies
        run: yarn install

      - name: Static HTML export with Nuxt
        run: yarn run generate

      - name: Deploy to VM
        run: |
          sudo apt-get install -y ssh rsync
          echo "$DEPLOY_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          rsync -avz -e 'ssh -i deploy_key.pem -o StrictHostKeyChecking=no' --exclude='.git' ./.output/public ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}
#          rsync -avz -e 'ssh -i deploy_key.pem -o StrictHostKeyChecking=no' --exclude='.git' ./nginx.conf ${{ env.HOST }}:${{ env.NGINX_DIRECTORY }}
#          sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled
#          sudo nginx -s reload
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: List workspace contents
        run: |
          echo "Listing deployment folder contents:"
          ls -la
